baseURL = "https://hyoromo.github.io/sound-game-training-android/"
publishDir = "docs"
languageCode = "en-us"
theme = "hugo-theme-learn"
googleAnalytics = 'G-0D4KL8KE9M'

defaultContentLanguage = "en"
metaDataFormat = "yaml"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
  unsafe = true

[params]
  # Author of the site, will be used in meta information
  author = "hyoromo"
  # Description of the site, will be used in meta information
  description = "Sound game training app"
  # Shows a checkmark for visited pages on the menu
  showVisitedLinks = false
  # Disable search function. It will hide search bar
  disableSearch = false
  # Javascript and CSS cache are automatically busted when new version of site is generated.
  # Set this to true to disable this behavior (some proxies don't handle well this optimization)
  disableAssetsBusting = false
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = false
  # A title for shortcuts in menu is set by default. Set this to true to disable it.
  disableShortcutsTitle = false
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton = false
  # Hide breadcrumbs in the header and only show the current page title
  disableBreadcrumb = true
  # Hide Next and Previous page buttons normally displayed full height beside content
  disableNextPrev = true
  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby = "weight"
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "mine"
  # Provide a list of custom css files to load relative from the `static/` folder in the site root.
  custom_css = ["css/foo.css", "css/bar.css"]

[Languages]
[Languages.en]
title = "Sound Game Training for Android"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-home'></i> General Site"
url = "https://hyoromo.github.io/sound-game-training-universal/"
weight = 9

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-smile'></i> Character Introduction"
url = "https://hyoromo.github.io/sound-game-training-android/chara"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-sticky-note'></i> Credits"
url = "https://hyoromo.github.io/sound-game-training-android/credits"
weight = 11

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-coffee'></i> Tip"
url = "https://hyoromo.github.io/sound-game-training-android/tip"
weight = 12

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-book'></i> Privacy Policy"
url = "https://hyoromo.github.io/sound-game-training-android/privacy"
weight = 13


[Languages.jp]
title = "音ゲートレーニング for Android"
weight = 2
languageName = "日本語"

[[Languages.jp.menu.shortcuts]]
name = "<i class='fas fa-home'></i> 総合サイト"
url = "https://hyoromo.github.io/sound-game-training-universal/jp/"
weight = 9

[[Languages.jp.menu.shortcuts]]
name = "<i class='fas fa-smile'></i> キャラ紹介"
url = "https://hyoromo.github.io/sound-game-training-android/jp/chara"
weight = 10

[[Languages.jp.menu.shortcuts]]
name = "<i class='fas fa-sticky-note'></i> クレジット"
url = "https://hyoromo.github.io/sound-game-training-android/jp/credits"
weight = 11

[[Languages.jp.menu.shortcuts]]
name = "<i class='fas fa-coffee'></i> 投げ銭"
url = "https://hyoromo.github.io/sound-game-training-android/jp/tip"
weight = 12

[[Languages.jp.menu.shortcuts]]
name = "<i class='fas fa-book'></i> プライバシーポリシー"
url = "https://hyoromo.github.io/sound-game-training-android/jp/privacy"
weight = 13


[Languages.zh]
title = "音乐游戏培训 for Android"
weight = 3
languageName = "简体中文"

[[Languages.zh.menu.shortcuts]]
name = "<i class='fas fa-home'></i> 一般网站"
url = "https://hyoromo.github.io/sound-game-training-universal/zh/"
weight = 9

[[Languages.zh.menu.shortcuts]]
name = "<i class='fas fa-smile'></i> 人物介绍"
url = "https://hyoromo.github.io/sound-game-training-androidzh/chara"
weight = 10

[[Languages.zh.menu.shortcuts]]
name = "<i class='fas fa-sticky-note'></i> 片头"
url = "https://hyoromo.github.io/sound-game-training-android/zh/credits"
weight = 11

[[Languages.zh.menu.shortcuts]]
name = "<i class='fas fa-coffee'></i> 捐赠"
url = "https://hyoromo.github.io/sound-game-training-android/zh/tip"
weight = 12

[[Languages.zh.menu.shortcuts]]
name = "<i class='fas fa-book'></i> 隐私政策"
url = "https://hyoromo.github.io/sound-game-training-android/zh/privacy"
weight = 13


[Languages.zh-TW]
title = "音樂遊戲培訓 for Android"
weight = 4
languageName = "繁體中文"

[[Languages.zh-TW.menu.shortcuts]]
name = "<i class='fas fa-home'></i> 一般網站"
url = "https://hyoromo.github.io/sound-game-training-universal/zh-tw/"
weight = 9

[[Languages.zh-TW.menu.shortcuts]]
name = "<i class='fas fa-smile'></i> 人物介紹"
url = "https://hyoromo.github.io/sound-game-training-android/zh-tw/chara"
weight = 10

[[Languages.zh-TW.menu.shortcuts]]
name = "<i class='fas fa-sticky-note'></i> 片頭"
url = "https://hyoromo.github.io/sound-game-training-android/zh-tw/credits"
weight = 11

[[Languages.zh-TW.menu.shortcuts]]
name = "<i class='fas fa-coffee'></i> 捐贈"
url = "https://hyoromo.github.io/sound-game-training-android/zh-tw/tip"
weight = 12

[[Languages.zh-TW.menu.shortcuts]]
name = "<i class='fas fa-book'></i> 隱私政策"
url = "https://hyoromo.github.io/sound-game-training-android/zh-tw/privacy"
weight = 13


[Languages.ko]
title = "사운드 게임 교육 for Android"
weight = 2
languageName = "한국어"

[[Languages.ko.menu.shortcuts]]
name = "<i class='fas fa-home'></i> 종합 사이트"
url = "https://hyoromo.github.io/sound-game-training-universal/ko/"
weight = 9

[[Languages.ko.menu.shortcuts]]
name = "<i class='fas fa-smile'></i> 캐릭터 소개"
url = "https://hyoromo.github.io/sound-game-training-android/ko/chara"
weight = 10

[[Languages.ko.menu.shortcuts]]
name = "<i class='fas fa-sticky-note'></i> 크레딧 표시"
url = "https://hyoromo.github.io/sound-game-training-android/ko/credits"
weight = 11

[[Languages.ko.menu.shortcuts]]
name = "<i class='fas fa-coffee'></i> 기부"
url = "https://hyoromo.github.io/sound-game-training-android/ko/tip"
weight = 12

[[Languages.ko.menu.shortcuts]]
name = "<i class='fas fa-book'></i> 개인 정보 정책"
url = "https://hyoromo.github.io/sound-game-training-android/ko/privacy"
weight = 13
